apiVersion: v1
kind: Service
metadata:
  name: nexus-api
  namespace: staging
spec:
  selector:
    app: nexus-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
